### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by dqcenter** [konstk1/helium-dashboard#13]
Any chance to add a docker compose file for whole stack? Thanks

**Comment by konstk1** [comment]
I personally wasn't planning on it right now. But, feel free to put in a PR if you get something going.

**Comment by benisai** [comment]
I agree. I would love this in docker.

**Comment by ThomDietrich** [comment]
There was an example here: https://github.com/konstk1/helium-dashboard/pull/9

My current production config (using [my fork](https://github.com/ThomDietrich/helium-exporter-grafana)) looks like this:
```yaml
  helium-poller:
    build:
      context: ./helium-dashboard
      labels:
        - autoheal=false
    image: helium-dashboard:latest
    depends_on:
      - influxdb
    environment:
      INFLUX_HOST: ${MONITORING_HOST}
      INFLUX_PORT: 8086
      INFLUX_BUCKET: helium
      INFLUX_ORG: kntinternet
      INFLUX_TOKEN: ${INFLUX_WRITE_TOKEN}
      HELIUM_WALLET: ${HELIUM_WALLET}
      HELIUM_HOTSPOT: ${HELIUM_HOTSPOT}
      HELIUM_ACTIVITY_LOOKBACK_HOURS: 8
      #DEBUG_TO_CONSOLE: 1
      TZ: Europe/Berlin
```
